name: Test

on:
  push:
    branches-ignore:
      - renovate/**
    paths:
      - ".github/workflows/test.yaml"
      - "go.mod"
      - "go.sum"
      - "Taskfile.yaml"
      - "**.go"
      - "**.go.json"
  pull_request:
    branches:
      - master
    paths:
      - ".github/workflows/test.yaml"
      - "go.mod"
      - "go.sum"
      - "Taskfile.yaml"
      - "**.go"
      - "**.go.json"

jobs:
  "go118":
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go_version: ["~1.18", ">=1.19-rc.2"]
    steps:
      - uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: "${{ matrix.go_version }}"
          stable: false
          check-latest: true
          cache: true

      - run: go test -count=1 -v ./...
        working-directory: ./internal/test/go118

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go_version: ["~1.17", "~1.18", ">=1.19-rc.2"]

    steps:
      - uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: "${{ matrix.go_version }}"
          check-latest: true
          cache: true

      - run: go test -coverpkg=./... -covermode=atomic -coverprofile=coverage.out -count=1 ./...

      - uses: codecov/codecov-action@v3
        with:
          files: coverage.out
